### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Kigs-framework/kigs#8]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [BuildShaderStruct](https://github.com/Kigs-framework/kigs/blob/b72b23781d73705f64ec05df8fdfbb6471031ce6/framework/Renderer/Headers/Shader.h#L137 "Destructor for BuildShaderStruct")
- [HTTPAsyncRequest](https://github.com/Kigs-framework/kigs/blob/54c9457069cf54453fdfb6e545b619be38f83a30/framework/HTTPRequest/Sources/HTTPAsyncRequest.cpp#L9 "Destructor for HTTPAsyncRequest")
- [TinyImage](https://github.com/Kigs-framework/kigs/blob/54c9457069cf54453fdfb6e545b619be38f83a30/framework/TinyImage/Sources/TinyImage.cpp#L40 "Destructor for TinyImage")

**Comment by Kigs-framework** [comment]
Thank you, I've fixed the ones you signaled, probably there is more.
I mainly work on the Kigs-NextGen branch at the moment to "modernize" parts of the code, setup namespace, remove obsolete code...

**Comment by elfring** [comment]
>…, probably there is more.

Another source code example:
https://github.com/Kigs-framework/kigs/blob/73688c1e8f404e7d3081186aa0f122b74c73d231/framework/PlatformsModules/Windows/Platform/TinyImage/PNGClassLoader.inl.h#L11

:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?
